### ISSUE TITLE
Resources from recurly.com are being blocked

### ISSUE THREAD

**Issue by chrissrogers** [duckduckgo/duckduckgo-privacy-extension#471] opened 2020-07-22 21:30 UTC
## Description
Resources from the recurly.com TLD are being blocked by the privacy extension.

Since https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/632026dfb7a3279ed6937a3ff35239309a5806d6, resources such as https://js.recurly.com/v4/recurly.js are being blocked on merchants' payment forms, preventing payment functionality when using the privacy extension.

## Steps to Reproduce
1. Visit a site using recurly.js not on the recurly.com domain. For example, https://recurly-examples-demo-0.herokuapp.com/minimal/index.html
2. Observe that the credit card form field is absent

**Expected behavior:**
As a customer, I should be able to input my credit card information into the form field.

**Actual behavior:**
The resource https://js.recurly.com/v4/recurly.js has been blocked by the extension, preventing the payment form from initializing.

**Versions**

- Extension: 2020.7.9
- Browser: Chrome
- OS: MacOS

## Additional Information
Similar issue: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/457

**Comment by chrissrogers** [comment] 2020-12-28 20:05
Pinging for more attention if possible. Thank you for everything you do!

**Comment by Taytay** [comment] 2021-02-08 21:51
I'd like to ask about this as well. It is biting our customers when they try to purchase. We're all for privacy, but we use Recurly to take payments in YNAB ([www.youneedabudget.com](www.youneedabudget.com)), and Recurly.js is the most secure way for us to take payments (rather than hosting the fields ourselves). Is there a workaround we can suggest to our customers besides disabling the extension?

**Comment by Charlie-belmer** [comment] 2021-02-10 01:36
Although this issue is still open, I don't believe recurly is still blocked. Can you give me some more details on what you are seeing on YNAB? 

Today, I tried creating a YNAB account with the extension installed on the latest Chrome, then went to account -> subscribe and was able to see network requests to recurly. Everything seemed to work, though I didn't complete the full checkout flow (it did seem to run a CC validation check).

If you can give me some more details about where your users are seeing issues, and any technical information you can gather, it would help me figure it out.

Thanks!

**Comment by arsendovlatyan** [comment] 2021-02-11 19:08
@Charlie-belmer we had the same issue report by one for our customers (Sep 2, 2020)  at https://meandmygolf.com/ , where we are using Recurly.JS as well. Here is the message and the screen-shot by the customer.

> I use DuckDuckGo (DDG) as my search engine. It has a privacy plug-in for Chrome. I had disable all of my other privacy software except for DDG. Once I disable DDG, I was able to proceed on MMG website and subscribe. I have since re-enabled DDG and other privacy software and the site appears to be running smoothly at the moment.

![image](https://user-images.githubusercontent.com/1083615/107685769-d00c0700-6cbd-11eb-9564-24208d75e2cb.png)

Actually, I was unable to reproduce the issue at that time as well, I was using Chrome on Windows.

Hope this helps.

**Comment by Taytay** [comment] 2021-02-11 22:52
Oh how odd! When it does impact our customers, some of our CC fields just don't show up. I'll do more digging on our end to verify whether this is a stale report or a case of blaming the wrong extension. 
Thanks @Charlie-belmer and @arsendovlatyan for responding here!

**Comment by Charlie-belmer** [comment] 2021-02-12 20:59
Please let me know if you do find anything in recent past, and I'll re-investigate!

**Comment by rborer** [comment] 2021-02-13 10:30
Howdy, I tested again on https://paper.li/ where I initially saw the blocking & Recurly resources are not blocked anymore. So from my point of view the issue is now solved.

**Comment by Charlie-belmer** [comment] 2021-02-15 14:55
Thanks for looking into this again @rborer! I'll go ahead and close this, but anyone who sees something similar in the future, please let us know.

**Closed by Charlie-belmer** 2021-02-15 14:55 UTC
