### ISSUE TITLE
"Manage Whitelist" and "Extension Options" links not working in Chrome 66.0.3350.0

### ISSUE THREAD

**Issue by justingarrick** [duckduckgo/duckduckgo-privacy-extension#151] opened 2018-02-27 13:14 UTC
In Chrome `66.0.3350.0`, the _Extension Options_ and _Manage Whitelist_ links attempt to open `chrome-extension://<ID>/html/options.html` in a new tab, which immediately closes because it is invalid.  Based on other extensions, it looks like the proper equivalent is `chrome://extensions/?options=<ID>`.

**Comment by alohaas** [comment] 2018-03-02 18:26
Thanks for your feedback @justingarrick. We handle bug reports internally so I'm bringing this to the team. I should note that I was unable to reproduce this issue in Chrome 66.0.3359.0. Though I realize this isn't your exact version, I assume you're using Chrome Canary. Please let me know whether or not you're still experiencing it.

**Comment by justingarrick** [comment] 2018-03-12 18:04
Thanks @alohaas, this seems to be resolved in `66.0.3359.22`.

**Comment by arpitjindal97** [comment] 2018-03-20 15:47
I am using latest [Chromium](https://www.archlinux.org/packages/extra/x86_64/chromium/) on Arch Linux. Similar issue exists. Clicking on _Manage Whitelist_ link opens a new tab with this url. 

`chrome-extension://<ID>/html/options.html`

It doesn't closes as long as I am on that tab but when I switch to another tab, it closes.

**Comment by jonathanKingston** [comment] 2021-12-30 23:16
Closing this out as I can't reproduce.

**Closed by jonathanKingston** 2021-12-30 23:16 UTC
Labels: reported
