### ISSUE TITLE
HubSpot calendar embed blocked by Chrome extension

### ISSUE THREAD

**Issue by jdinbound** [duckduckgo/duckduckgo-privacy-extension#2608] opened 2024-08-06 14:56 UTC
## Description

Hello. I found a past Issue in this repo about this extension blocking HubSpot CTAs. It may now also be blocking the embedded scheduler tool. I was first notified of this by a colleague and was able to reproduce it on my machine. With the extension on, it blocks the embedded HubSpot meeting scheduler tool. 

I've embedded it two different ways here (with two different schedulers and HS accounts) and it is blocked both ways with extension on: 
https://smartinbound.com/testing/

And here was the original bug found: 
https://sittadel.com/start/

## Steps to Reproduce

1. Visit either of the above webpages with the extension on, OR
2. Embed the HubSpot scheduler on any website 
3. Activate the Privacy Essentials plugin on Chrome

**Expected behavior:**
The scheduler should show. 

**Actual behavior:**
The scheduler does not show. 

**Versions**

- Extension: 2024.7.24
- Browser: Chrome 
- OS: Mac 

## Additional Information

It is repeatable, no console errors, unsure about upgrade (was referred to this issue by an extension user, I am the web dev)

<img width="1459" alt="Screenshot 2024-08-06 at 10 54 45 AM" src="https://github.com/user-attachments/assets/f9f68729-28a8-4416-9293-4ffe2bb29db6">
<img width="1450" alt="Screenshot 2024-08-06 at 10 54 59 AM" src="https://github.com/user-attachments/assets/1ebc6175-ac41-479b-b9a4-9804538da1c1">

**Comment by dharb** [comment] 2024-08-06 15:12
Thanks for the report, and our apologies for the trouble! Really appreciate the links to repro. We'll get a fix out for this ASAP.

**Comment by jdinbound** [comment] 2024-08-06 15:22
@dharb Incredible, thank you much!

**Comment by dharb** [comment] 2024-08-06 15:55
@jdinbound we just merged a fix in https://github.com/duckduckgo/privacy-configuration/pull/2224, it will roll out to clients over the next 15-30 mins. Any chance you could confirm that the issue is fully resolved?

We'd love to send you a free DuckDuckGo t-shirt for taking the time to submit such a thorough report. If you're interested, shoot me an email at the address I used in the test form with your size and where to send it.

**Comment by jdinbound** [comment] 2024-08-06 16:46
Confirmed resolved on both my sites! Thanks for the fast work. Very happy to help, love your mission. I will absolutely email you haha :)

**Comment by dharb** [comment] 2024-08-07 12:28
Thanks for confirming! Closing as fixed.

**Closed by dharb** 2024-08-07 12:28 UTC
