### ISSUE TITLE
Search bar doesn't work in incognito mode

### ISSUE THREAD

**Issue by vtwang** [duckduckgo/duckduckgo-privacy-extension#461] opened 2020-06-22 19:18 UTC
## Description

Typing in the address bar/search bar is supposed to automatically search using duckduckgo if it is not a web address. This does not work in incognito mode.

## Steps to Reproduce

1. Open incognito mode
2. Type "hamilton" into the address bar
3. Press enter

**Expected behavior:**

Uses duckduckgo to search for "hamilton"

**Actual behavior:**

```
This site can’t be reached
hamilton’s server IP address could not be found.
```

**Versions**

- Extension: 2020.5.28
- Browser: Brave
- OS: Mac

## Additional Information

`ALT + CMD + F` shortcut crashes the browser in incognito mode. This is the shortcut for `search the web`. The shortcut works normally without incognito mode.

**Comment by dharb** [comment] 2020-06-23 16:36
Thanks for letting us know. I suspect it may be something on Brave's side since the issue isn't present in other Chromium based browsers. I'll get to the bottom of what's going on here and get it resolved.

**Comment by jonathanKingston** [comment] 2021-12-30 23:18
I can't reproduce this anymore, I know since this has been filed there have been fixes for Brave extension issues.

Closing this out, if it's still reoccurring please let us know.

**Closed by jonathanKingston** 2021-12-30 23:18 UTC
