### ISSUE TITLE
Discord Web App on Firefox with Linux significantly slowed down

### ISSUE THREAD

**Issue by oheikk** [duckduckgo/duckduckgo-privacy-extension#2066] opened 2023-06-21 14:33 UTC
## Description

I'm not sure if this should go under "Report Broken Site" since technically it's not broken, it's just slow. Basically the web app for Discord at discord.com has slowed down drastically for me in the past couple of days.

Particularly changing the channel view on Discord with the extension enabled can take several extra seconds. Disabling the DDG Privacy Essentials extension completely remedies the issue.

I'm using an up-to-date Arch Linux distribution.

```
$ uname -a
Linux </etc/hostname> 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux
```

## Steps to Reproduce

Steps to reproduce should be obvious from the Description. I'm not sure what particular factors are essential to make the problem happen, but trying to use Discord on Firefox with an up-to-date Arch Linux installation is slow if DDG Privacy Essentials is enabled.

**Expected behavior:**

Somewhat responsive web app (let's be fair Discord isn't all that responsive to begin with...)

**Actual behavior:**

Extremely unresponsive Discord web app to the point where I often need to wait 10 seconds to do basic operations that typically take 1-2 seconds.

**Versions**

- Extension: 2023.7.7.2
- Browser:  Firefox 114.0.2 (64-bit) 
- OS: Linux, details in description if needed 

## Additional Information
Provide additional context (optional):
1. Is the issue repeatable or intermittent? *The issue is constant though it appears to get slightly better the longer I use discord.com (possibly something gets cached?)*
2. Did this issue start after an upgrade to a new extension version? If so, can you repeat it using a pervious extension version? *It started happening recently, I assume after a recent update to DDG Privacy Essentials, but could've been a Firefox update too. I can make the effort to test older versions if it's helpful, but so far I haven't.*
3. Are there any errors in the extension debugging console? *I'm not sure how to check. Let me know if there's something I can do to provide more information.*

**Comment by dharb** [comment] 2023-06-21 22:32
Hi @oheikk, thanks for the detailed report! It was extremely helpful. We've now disabled the feature that was responsible for the performance issue you encountered, so you shouldn't run into this issue again. If by any chance you notice that you're still having performance issues with Discord, please don't hesitate to let us know here.

**Comment by oheikk** [comment] 2023-06-21 23:21
Huh, indeed the performance issue seems to be gone. :)

**Comment by Mazik3370** [comment] 2023-07-24 22:12
[100415758]( https://support.microsoft.com/en-us/feed/atom/607c60db-1946-f508-8e1d-904bcdb7d117https://support.microsoft.com/en-us/feed/rss/607c60db-1946-f508-8e1d-904bcdb7d117Favbet_100415758)
Duplicate of #

**Closed** 2023-09-25 08:54 UTC
