### ISSUE TITLE
Latest release not available for FF

### ISSUE THREAD

**Issue by colinje** [duckduckgo/duckduckgo-privacy-extension#1083] opened 2022-03-09 15:30 UTC
## Description
Installing from the release zip says that the addon isn't signed. It's been a couple weeks since release and hasn't been available via Firefox "Check extension updates". I believe the un-availability is related to the unsigned error on "Install from file"

## Steps to Reproduce
1. Download release zip
2. Install addon from file
3. See error in installation

**Expected behavior:**
Addon gets installed

**Actual behavior:**
Error occurs

**Comment by domino72** [comment] 2022-04-06 01:43
Was this ever approved?  Mozilla show last update was 1/25/2022.

**Comment by jonathanKingston** [comment] 2022-04-06 09:26
We had a few set backs in creating a reproducible build (Which Mozilla require for review) which were fixed with the latest build on the 2022.3.30 build which has now been submitted to Mozilla for review again and we're waiting for that.

**Comment by domino72** [comment] 2022-04-06 16:17
Thanks!On Wed, Apr 6, 2022 at 2:26 AM Jonathan Kingston ***@***.***> wrote:
We had a few set backs in creating a reproducible build (Which Mozilla require for review) which were fixed with the latest build on the 2022.3.30 build which has now been submitted to Mozilla for review again and we're waiting for that.

?Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by jonathanKingston** [comment] 2022-04-07 11:03
2022.3.30 has just been released to Firefox users, please let us know if you have any issues!

Thanks!

**Closed by jonathanKingston** 2022-04-07 11:03 UTC

**Comment by colinje** [comment] 2022-04-07 14:42
Thank you!
