### ISSUE TITLE
Allowlist doesn't handle hosts or domains ending with www

### ISSUE THREAD

**Issue by ladamski** [duckduckgo/duckduckgo-privacy-extension#427] opened 2020-02-08 23:18 UTC
## Description
Unanchored stripping of www. causes issues with hosts or domains that end with www

## Steps to Reproduce
1. Try to add 'testwww.com' to the allowlist, get an error
or
2. Try to add 'alpha-www.test.com' to allowlist, get 'alpha-test.com' 

![image](https://user-images.githubusercontent.com/1753954/74093334-6db67000-4a85-11ea-8e48-2c927d3d8f02.png)

**Expected behavior:**
Those domains should be added to the allowlist without modification

**Actual behavior:**
Errors or domains are modified as not intended.

**Versions**

- Extension: 2019.12.12
- Browser: All
- OS: All

## Additional Information
I have a simple proposed fix in a PR that I will link here

**Comment by jonathanKingston** [comment] 2021-12-30 23:14
Closing this out as can't reproduce and the PR seems to have fixed this.

**Closed by jonathanKingston** 2021-12-30 23:14 UTC
