### ISSUE TITLE
DuckDuckGo doesn't show up in Firefox's search engine list

### ISSUE THREAD

**Issue by cranderson** [duckduckgo/duckduckgo-privacy-extension#729] opened 2021-07-08 22:58 UTC
## Description
DuckDuckGo doesn't show up in the list of search engines selectable from the Firefox preferences.

## Steps to Reproduce

1. add DuckDuckGo firefox extension
2. click magnifying glass in firefox search box
3. click Change Search Settings

**Expected behavior:**
DuckDuckGo should be available as an option to select for the Default Search Engine

**Actual behavior:**
Only Google shows up in the list under Default Search Engine

**Versions**

- Extension: 2021.7.5
- Browser: Firefox 89.0.2 (64-bit)
- OS: Fedora

## Additional Information
Restarted firefox, no change.

**Comment by samuraikenneth73** [comment] 2021-07-15 14:55
Hello,

I have followed the steps to reproduce and I was able to find and select duckduckgo as default search engine in Firefox
Using Firefox version 89.0.1 (64-bit), Windows 10

![duckduckgo](https://user-images.githubusercontent.com/42445454/125809296-3605836b-1754-4b76-8e91-c8c6a0104b63.JPG)

**Comment by Nihal247** [comment] 2021-07-27 14:47
Hi @cranderson and thank you for your patience.

Make sure you haven't removed DuckDuckGo from Search Shortcuts.

![Screenshot (13)_LI](https://user-images.githubusercontent.com/80682093/127174904-efa02e36-d531-4dbc-be79-d166f5eaf013.jpg)

If you have click on **Restore Default Search Engines**, then choose DuckDuckGo as your **Default Search Engine**.

Thank you in advance.

**Comment by jonathanKingston** [comment] 2021-08-08 21:23
@cranderson can you check if the support by @Nihal247 works?

Thanks!

**Comment by jonathanKingston** [comment] 2021-12-30 21:51
Closing as this works for me.

**Closed by jonathanKingston** 2021-12-30 21:51 UTC
