### ISSUE TITLE
Firefox: forbidden page

### ISSUE THREAD

**Issue by marsip** [duckduckgo/duckduckgo-privacy-extension#418] opened 2019-11-25 10:45 UTC
## Description
When searching DuckDuckGo HTML I get a "forbidden" page.

## Steps to Reproduce

1. Highlight a text on page.
2. Right click, and select DuckDuckGo HTML search
3. Page with word "forbidden" is shown.

**Expected behavior:**

A valid search

**Actual behavior:**

Se above.

**Versions**
2019.9.12
Firefox 70.0.1 (64-bit, Swedish version), in Windows 10, version 1909.

## Additional Information

1. Is the issue repeatable or intermittent?
Repeatable

2. Did this issue start after an upgrade to a new extension version? If so, can you repeat it using a pervious extension version?
Don't know.

3. Are there any errors in the extension debugging console?
Don't know how to use.

**Comment by mwuttke97** [comment] 2021-03-24 12:29
I don't use the extension, but my Firefox also uses the header `Origin: null` if I `right-click some selected text -> Search DuckDuckGo HTML for ...`. If I open the devtools and repeat the request, I can manually set `Origin: https://html.duckduckgo.com`, which yields the correct response (however, not shown in the browser). However, setting `network.http.sendOriginHeader` to 0 or 1 didn't solve the problem for me.

**Comment by jonathanKingston** [comment] 2021-12-30 21:58
I can't reproduce this in Firefox, closing. Please provide some more details if this is still occurring.

**Closed by jonathanKingston** 2021-12-30 21:58 UTC

**Comment by adrianlshaw** [comment] 2021-12-30 23:08
I used to have this issue and can confirm it's no longer a problem
