### ISSUE TITLE
make this extension for firefox android also

### ISSUE THREAD

**Issue by vilgad** [duckduckgo/duckduckgo-privacy-extension#698] opened 2021-06-19 10:08 UTC
i love this extension too much on my desktop but please make it **available** for **firefox android** also.
Because the _duckduckgo browser is very simple_. it increases privacy protection but the browsing experience is not that much great. i **love firefox on android and desktop both**, it is also **very good for privacy** so can you **_please make this **_extension available for android firefox also._**_**

**Comment by Nihal247** [comment] 2021-07-07 05:29
Yes I agree with you @Rohit-codeboy, having this extension for Firefox Android will be a privacy boon.

**Comment by Nihal247** [comment] 2021-07-29 05:01
Although you can get the extension using Firefox Nightly Android.

**Comment by jonathanKingston** [comment] 2021-12-30 23:34
This is a duplicate of https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/174 I'll close this out and respond there.

Thanks for raising!

**Closed by jonathanKingston** 2021-12-30 23:34 UTC
