### ISSUE TITLE
Chrome extension lock the default search engine configuration

### ISSUE THREAD

**Issue by akhabali** [duckduckgo/duckduckgo-privacy-extension#492] opened 2020-09-21 09:03 UTC
## Description
The extension lock the default search engine when activated.

## Steps to Reproduce

1. install the chrome extension
2. try to change the default search engine without disabling the extension

**Expected behavior:**

I want to be able to use the extension to block the trackers and still use different default search engine.

**Actual behavior:**

Default search engine is locked with duckduckgo.com

**Versions**
2020.8.12

- Extension: 2020.8.12
- Browser: Chrome 
- OS:  Windows

**Comment by 6gfd8** [comment] 2021-02-26 22:32
Remove these [lines](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/5d95bc0126bfd54b224d0584c83108c794862521/browsers/chrome/manifest.json#L26-L37) should remove this [behavior](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/239#issuecomment-494521965).

This is the exact reason I switched back to AdGuard (which uses [more resources](https://www.debugbear.com/blog/2020-chrome-extension-performance-report#performance-impact-of-ad-blockers) than the DDG Privacy Essentials), but I doubt they will remove it (it seems [some people]((https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/239) actually prefer this) from the official release.

**Comment by pointydev** [comment] 2021-08-05 18:51
I'd also like to express my support for an option to disable this functionality easily, as it's annoying to have to edit source or set a browser policy in order to work around it.

**Comment by sammacbeth** [comment] 2021-08-06 08:43
This is a Chrome limitation - if we want to change the default search engine on install we have to set this `is_default` flag. However, once we set this Chrome will lock the search engine choice.

There are a couple of workarounds if you want to keep the extension's privacy protections but not use our search all the time:
 1. Use our `!` bangs to redirect to different search engines when you need them
 2. Install _another_ extension that changes the default search engine, which will then unlock your search setting in Chrome.

**Comment by jonathanKingston** [comment] 2022-09-24 12:59
Closing as a duplicate of: #90

**Closed by jonathanKingston** 2022-09-24 12:59 UTC
