### ISSUE TITLE
Add to Calendar Goggle Calendar 400 response

### ISSUE THREAD

**Issue by wolfe111** [duckduckgo/duckduckgo-privacy-extension#706] opened 2021-07-02 09:27 UTC
## Description
Extension overrides the URL to Google Calendar from Add to Calendar button, which results in google calendar returning a 400. https://www.addevent.com/help/article/139/getting-400-error-when-trying-to-add-to-a-google-calendar

## Steps to Reproduce

1. With this extension installed and active, using either of the browsers, go to https://www.addevent.com/add-to-calendar-button
2. Scroll down to the Example section, click on the Add to Calendar buttob
3. Click on Google from the dropdown

**Expected behavior:**
Taken to Google Calendar with details of the calendar event showing

**Actual behavior:**
400 response from Google

**Versions**
DDG 2021.6.2 in Chrome, which is my default browser.

**Comment by sammacbeth** [comment] 2021-07-02 17:05
Thanks for the report. I was able to reproduce the issue and traced the cause down to our 3rd party cookie blocking being a little too aggressive. We'll get out a fix for this ASAP.

**Closed** 2021-07-05 14:41 UTC
